<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMR6sV07\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMR6sV07/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMR6sV07.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMR6sV07\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMR6sV07\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MR6sV07',
    'container.build_id' => '7e880cef',
    'container.build_time' => 1516007814,
));
