<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCVnRwPH\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCVnRwPH/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCVnRwPH.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCVnRwPH\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCVnRwPH\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CVnRwPH',
    'container.build_id' => 'a50d654b',
    'container.build_time' => 1515822619,
));
