<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYrljJOQ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYrljJOQ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYrljJOQ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYrljJOQ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYrljJOQ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'YrljJOQ',
    'container.build_id' => 'bd49bc48',
    'container.build_time' => 1515824621,
));
